version: 2
jobs:
  buildAndDeploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo apt update
      - run: sudo apt install -y python-pip python-dev
      - run:
          name: Install awscli
          command: sudo pip install awscli

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: npm run build
      - run: aws s3 sync ./build s3://momoweb.com

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

workflows:
  version: 2
  test_build_and_deploy:
      jobs:
        - buildAndDeploy:
            filters:
              branches:
                only:
                  - master
